name: Elixir CI

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MIX_ENV: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.9.x' # Define the elixir version [required]
        otp-version: '22.x' # Define the OTP version [required]

    - name: Install Dependencies
      run: mix deps.get --only test

    - name: Compile
      run: mix compile

    - name: Run Tests
      run: mix coveralls.github
